# Generated by Django 6.0.1 on 2026-01-31 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_deducted_at',
            field=models.DateTimeField(blank=True, help_text='Fecha/hora en la que se descontó stock para este pedido (idempotencia).', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='created', max_length=20),
        ),
    ]
