# Generated by Django 5.2.11 on 2026-04-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wompi_transaction_id',
            field=models.CharField(blank=True, default='', help_text='ID de transacción Wompi (asignado por webhook).', max_length=120),
        ),
    ]
