# Generated by Django 6.0.1 on 2026-02-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Referencia única del pago (asignada al confirmar).', max_length=80, null=True, unique=True),
        ),
    ]
