# Generated by Django 5.2.11 on 2026-02-17 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('document_type', models.CharField(blank=True, default='CC', help_text='Tipo de documento principal del cliente (CC, NIT, ...).', max_length=10)),
                ('cedula', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='La cédula debe contener solo números (5 a 20 dígitos).', regex='^\\d{5,20}$')])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['document_type', 'cedula'], name='idx_customer_doc')],
                'constraints': [models.UniqueConstraint(fields=('document_type', 'cedula'), name='uniq_customer_document_type_cedula')],
            },
        ),
    ]
