# Generated by Django 6.0.1 on 2026-02-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
