# Generated by Django 6.0.1 on 2026-02-04 00:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cedula',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe contener solo números (5 a 20 dígitos).', regex='^\\d{5,20}$')]),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('cedula', ''), _negated=True), name='customer_cedula_not_empty'),
        ),
    ]
