# Generated by Django 6.0.1 on 2026-02-11 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_document_type'),
        ('customers', '0003_alter_customer_cedula_and_more'),
    ]

    operations = [
    ]
