# Generated by Django 6.0.1 on 2026-02-14 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_merge_20260211_1405'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='customer_cedula_not_empty',
        ),
        migrations.AlterField(
            model_name='customer',
            name='cedula',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='La cédula debe contener solo números (5 a 20 dígitos).', regex='^\\d{5,20}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['document_type', 'cedula'], name='idx_customer_doc'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('document_type', 'cedula'), name='uniq_customer_document_type_cedula'),
        ),
    ]
