"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

from urllib.parse import urlparse
from email.utils import parseaddr

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from a .env file located at the project root
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() in ("1", "true", "yes", "on")

# SECURITY WARNING: keep the secret key used in production secret!
# En producción (DEBUG=False) la app falla hard si DJANGO_SECRET_KEY no está configurado.
if not DEBUG:
    SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]
else:
    SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-change-me")

 # Explicit allowed hosts for local dev + LAN access
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    *([os.getenv("DJANGO_LAN_IP")] if os.getenv("DJANGO_LAN_IP") else []),
    "0.0.0.0",
]

# Allow extra hosts via env if provided
raw_allowed_hosts = os.getenv("DJANGO_ALLOWED_HOSTS", "")
if raw_allowed_hosts:
    ALLOWED_HOSTS += [
        h.strip() for h in raw_allowed_hosts.split(",") if h.strip()
    ]

# CSRF trusted origins (needed when exposing via HTTPS tunnels / reverse proxies)
 # CSRF trusted origins for frontend access (local + LAN)
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://192.168.20.128:3000",
]

# Allow extra trusted origins via env if provided
raw_csrf_trusted = os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "")
if raw_csrf_trusted:
    CSRF_TRUSTED_ORIGINS += [
        o.strip() for o in raw_csrf_trusted.split(",") if o.strip()
    ]

# When running behind a reverse proxy (e.g., Cloudflare Tunnel), Django should trust
# the forwarded proto header to know the original scheme was HTTPS.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Trust host/scheme forwarded by the proxy (Cloudflare Tunnel sets these headers)
USE_X_FORWARDED_HOST = True

# Avoid HTTPS redirect loops behind tunnels in dev/demo.
# In production you can set DJANGO_SECURE_SSL_REDIRECT=True.
SECURE_SSL_REDIRECT = os.getenv("DJANGO_SECURE_SSL_REDIRECT", "False").lower() in ("1", "true", "yes", "on")
if DEBUG:
    # Default to False in DEBUG unless explicitly enabled via env.
    SECURE_SSL_REDIRECT = os.getenv("DJANGO_SECURE_SSL_REDIRECT", "False").lower() in ("1", "true", "yes", "on")

# Cookie security flags
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = "Lax"

# For APIs behind proxies/rewrites (Next.js / Cloudflare Tunnel),
# disable Django's automatic slash-append redirects to avoid 301 loops.
APPEND_SLASH = False


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 2FA
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',
    'two_factor',

    'rest_framework',
    'imagekit',
    'storages',

    # local apps
    'apps.catalog.apps.CatalogConfig',
    'apps.orders.apps.OrdersConfig',
    'apps.customers.apps.CustomersConfig',
    'apps.common',
    'apps.admin_api.apps.AdminApiConfig',
]

MIDDLEWARE = [
    'config.middleware.AdminIPRestrictionMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = os.getenv("DATABASE_URL", "").strip()

if DATABASE_URL:
    # If the DB is local (Docker/localhost), Postgres typically does NOT support SSL.
    # For managed/prod DBs, keep SSL required by default.
    parsed_db = urlparse(DATABASE_URL)
    db_host = (parsed_db.hostname or "").strip().lower()
    is_local_db = db_host in {"localhost", "127.0.0.1", "0.0.0.0", "::1"}

    raw_ssl_require = os.getenv("DB_SSL_REQUIRE", "").strip().lower()
    if raw_ssl_require:
        ssl_require = raw_ssl_require in ("1", "true", "yes", "on")
    else:
        # Default policy: require SSL unless DB is local.
        ssl_require = not is_local_db

    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=int(os.getenv("DB_CONN_MAX_AGE", "600")),
            ssl_require=ssl_require,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / "staticfiles"

# =========================
# R2 / S3-compatible storage (Cloudflare R2)
# =========================

R2_BUCKET_NAME = os.getenv("R2_BUCKET_NAME", "")
R2_ACCESS_KEY_ID = os.getenv("R2_ACCESS_KEY_ID", "")
R2_SECRET_ACCESS_KEY = os.getenv("R2_SECRET_ACCESS_KEY", "")
R2_ACCOUNT_ID = os.getenv("R2_ACCOUNT_ID", "")

# Endpoint S3 compatible de R2
R2_ENDPOINT_URL = os.getenv(
    "R2_ENDPOINT_URL",
    f"https://{R2_ACCOUNT_ID}.r2.cloudflarestorage.com" if R2_ACCOUNT_ID else "",
)

# URL pública desde donde se servirán los archivos
R2_PUBLIC_BASE_URL = os.getenv("R2_PUBLIC_BASE_URL", "").rstrip("/")

# Derive the public media host for django-storages URL generation.
# Example R2_PUBLIC_BASE_URL: https://pub-xxxx.r2.dev
# We need only the hostname part (pub-xxxx.r2.dev).
R2_PUBLIC_MEDIA_HOST = ""
if R2_PUBLIC_BASE_URL:
    # Avoid importing urlparse at module top if not needed.
    from urllib.parse import urlparse

    parsed = urlparse(R2_PUBLIC_BASE_URL)
    R2_PUBLIC_MEDIA_HOST = parsed.netloc or parsed.path  # supports values with/without scheme
    R2_PUBLIC_MEDIA_HOST = R2_PUBLIC_MEDIA_HOST.strip("/")

AWS_ACCESS_KEY_ID = R2_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY = R2_SECRET_ACCESS_KEY
AWS_STORAGE_BUCKET_NAME = R2_BUCKET_NAME
AWS_S3_ENDPOINT_URL = R2_ENDPOINT_URL
AWS_S3_REGION_NAME = "auto"
AWS_S3_SIGNATURE_VERSION = "s3v4"

# IMPORTANT: Use the PUBLIC host for generating .url values (do NOT use the S3 endpoint host)
# This is what fixes the frontend 400s against *.r2.cloudflarestorage.com.
AWS_S3_CUSTOM_DOMAIN = R2_PUBLIC_MEDIA_HOST or None
AWS_S3_URL_PROTOCOL = "https:"

AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = False
AWS_S3_FILE_OVERWRITE = False
AWS_S3_OBJECT_PARAMETERS = {
    "CacheControl": "public, max-age=31536000, immutable",
}

# Django 4.2+ / 5 / 6
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "bucket_name": AWS_STORAGE_BUCKET_NAME,
            "access_key": AWS_ACCESS_KEY_ID,
            "secret_key": AWS_SECRET_ACCESS_KEY,
            "endpoint_url": AWS_S3_ENDPOINT_URL,
            "region_name": AWS_S3_REGION_NAME,
            "signature_version": AWS_S3_SIGNATURE_VERSION,
            # Generate public URLs using the public host (r2.dev or your custom domain)
            "custom_domain": AWS_S3_CUSTOM_DOMAIN,
            "url_protocol": AWS_S3_URL_PROTOCOL,
        },
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Backwards compatibility: some libs still read DEFAULT_FILE_STORAGE.
# Keep it aligned with STORAGES["default"] (R2/S3 compatible).
DEFAULT_FILE_STORAGE = "storages.backends.s3.S3Storage"

# ImageKit: generate cachefiles and store them in the default storage (R2 via STORAGES["default"]).
# Optimistic strategy generates on-demand and reuses if present.
IMAGEKIT_DEFAULT_CACHEFILE_STRATEGY = "imagekit.cachefiles.strategies.Optimistic"

# Feature flag: control eager cache for ProductImage via environment variable
ENABLE_PRODUCTIMAGE_EAGER_CACHE = os.getenv(
    "ENABLE_PRODUCTIMAGE_EAGER_CACHE",
    "False"
).lower() in ("1", "true", "yes", "on")

# MEDIA_URL debe apuntar a la URL pública del bucket
if R2_PUBLIC_BASE_URL:
    MEDIA_URL = f"{R2_PUBLIC_BASE_URL}/"
else:
    MEDIA_URL = "/media/"


# Django REST Framework
REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "apps.common.pagination.RelativePageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "1000/minute" if DEBUG else "60/minute",
        "checkout": "100/minute" if DEBUG else "5/minute",
        "stock_validate": "200/minute" if DEBUG else "30/minute",
    },
}


# Email configuration
#
# Contrato transaccional:
# - DEFAULT_FROM_EMAIL es la fuente de verdad base del remitente.
# - La entrega real de correos transaccionales debe resolverse desde una capa
#   explícita de aplicación usando Resend (no desde SMTP Gmail implícito).
# - Este archivo centraliza configuración y evita un fallback híbrido ambiguo.


def _extract_email_address(value: str) -> str:
    """Return the plain email address portion from a raw from-email string."""
    _, email_address = parseaddr((value or "").strip())
    return (email_address or "").strip().lower()


def _email_domain(value: str) -> str:
    email_address = _extract_email_address(value)
    if "@" not in email_address:
        return ""
    return email_address.split("@", 1)[1].strip().lower()


# Proveedor transaccional esperado por la app/servicio de notificaciones.
# En desarrollo se permite `console` para inspección local.
EMAIL_TRANSACTIONAL_PROVIDER = os.getenv("EMAIL_TRANSACTIONAL_PROVIDER") or (
    "console" if DEBUG else "resend"
)

# Clave/API base para integración explícita con Resend.
RESEND_API_KEY = os.getenv("RESEND_API_KEY", "")
RESEND_API_BASE_URL = os.getenv("RESEND_API_BASE_URL", "https://api.resend.com")

# Backend de Django solo para desarrollo local o uso explícito vía env.
# Importante: no caer automáticamente a SMTP en producción.
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND") or "django.core.mail.backends.console.EmailBackend"

# Fuente de verdad base del remitente.
_raw_default_from_email = os.getenv("DEFAULT_FROM_EMAIL") or (
    "Kame.col <soporte@kamecol.local>" if DEBUG else "Kame.col <soporte@kamecol.com>"
)

# Remitente transaccional explícito para Resend.
# Si el DEFAULT_FROM_EMAIL viene contaminado con Gmail u otro dominio no verificado,
# forzamos el dominio operativo de la marca para evitar errores 403 al enviar.
TRANSACTIONAL_FROM_EMAIL = os.getenv("TRANSACTIONAL_FROM_EMAIL", "").strip()
if not TRANSACTIONAL_FROM_EMAIL:
    default_from_domain = _email_domain(_raw_default_from_email)
    if EMAIL_TRANSACTIONAL_PROVIDER == "resend" and default_from_domain != "kamecol.com":
        TRANSACTIONAL_FROM_EMAIL = "Kame.col <soporte@kamecol.com>"
    else:
        TRANSACTIONAL_FROM_EMAIL = _raw_default_from_email

DEFAULT_FROM_EMAIL = TRANSACTIONAL_FROM_EMAIL
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Logging configuration
# https://docs.djangoproject.com/en/6.0/topics/logging/

# Create logs directory if it doesn't exist
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': LOGS_DIR / 'django.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'apps.orders': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.catalog': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.customers': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.notifications': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
}

# =========================
# Wompi — Pasarela de pagos
# =========================
# Dashboard: https://dashboard.wompi.co/app/en/developers
# WOMPI_PUBLIC_KEY    → frontend (Next.js)
# WOMPI_PRIVATE_KEY   → backend únicamente, NUNCA exponer al frontend
# WOMPI_EVENTS_SECRET → validar checksum del webhook entrante
# WOMPI_INTEGRITY_SECRET → generar firma para el Widget
WOMPI_PUBLIC_KEY = os.getenv("WOMPI_PUBLIC_KEY", "")
WOMPI_PRIVATE_KEY = os.getenv("WOMPI_PRIVATE_KEY", "")
WOMPI_EVENTS_SECRET = os.getenv("WOMPI_EVENTS_SECRET", "")
WOMPI_INTEGRITY_SECRET = os.getenv("WOMPI_INTEGRITY_SECRET", "")

# Storefront público (emails / enlaces desde Django). En producción: FRONTEND_SITE_URL o NEXT_PUBLIC_SITE_URL.
# En DEBUG, email_context solo usa FRONTEND_SITE_URL si la defines en el .env raíz; si no, localhost:3000.
FRONTEND_SITE_URL = os.getenv("FRONTEND_SITE_URL", os.getenv("NEXT_PUBLIC_SITE_URL", "")).strip().rstrip("/")
DEV_STOREFRONT_URL = os.getenv("DEV_STOREFRONT_URL", "").strip().rstrip("/")

# Two-factor auth
LOGIN_URL = 'two_factor:login'

# Admin IP allowlist — comma-separated IPs in ADMIN_ALLOWED_IPS env var.
# Leave empty to disable the restriction (e.g. local dev without the var set).
_raw_admin_ips = os.getenv("ADMIN_ALLOWED_IPS", "")
ADMIN_ALLOWED_IPS = {ip.strip() for ip in _raw_admin_ips.split(",") if ip.strip()}

# =========================
# Sentry (error monitoring)
# =========================
import logging

import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.logging import LoggingIntegration
from sentry_sdk.utils import BadDsn

SENSITIVE_KEYS = {"password", "card_number", "cvv", "email", "token"}


def _sentry_before_send(event, hint):
    try:
        data = event.get("request", {}).get("data", {})
        if isinstance(data, dict):
            for key in SENSITIVE_KEYS:
                if key in data:
                    data[key] = "[Filtered]"
    except Exception:
        pass
    return event


# Misma variable de entorno que en Render: SENTRY_DSN (valor local en .env, no commitear).
# Debe ser solo la URL del DSN (https://...@oXXXX.ingest.sentry.io/NNNNN), sin otras variables pegadas.
SENTRY_DSN_BACKEND = os.getenv("SENTRY_DSN", "").strip().strip('"').strip("'")
SENTRY_ENVIRONMENT = os.getenv("DJANGO_ENV", "production").strip()

if SENTRY_DSN_BACKEND:
    try:
        sentry_sdk.init(
            dsn=SENTRY_DSN_BACKEND,
            environment=SENTRY_ENVIRONMENT,
            integrations=[
                DjangoIntegration(),
                LoggingIntegration(
                    level=logging.INFO,
                    event_level=logging.ERROR,
                ),
            ],
            traces_sample_rate=0.2,
            profiles_sample_rate=0.1,
            send_default_pii=False,
            before_send=_sentry_before_send,
            debug=os.getenv("SENTRY_DEBUG", "").lower() in ("1", "true", "yes"),
        )
    except BadDsn as exc:
        logging.getLogger(__name__).warning(
            "Sentry omitido: SENTRY_DSN inválido (revisa Render: una sola línea, URL completa, "
            "sin pegar DJANGO_ENV u otras vars). Detalle: %s",
            exc,
        )
