# Generated by Django 5.2.11 on 2026-02-17 13:08

import apps.catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HomepageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=150)),
                ('subtitle', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('show_text', models.BooleanField(default=True, help_text='Si se desactiva, no se muestran título/subtítulo/descripcion aunque existan.')),
                ('image', models.ImageField(upload_to=apps.catalog.models.homepage_banner_upload_path)),
                ('alt_text', models.CharField(blank=True, default='', max_length=200)),
                ('cta_label', models.CharField(blank=True, default='', help_text="Texto del botón (por ejemplo, 'Ver colección').", max_length=80)),
                ('cta_url', models.CharField(blank=True, default='', help_text='Usa una ruta relativa. Ej: /catalogo (NO uses http(s)://, localhost, 127.0.0.1, 192.168.x.x ni dominios .trycloudflare.com).', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el carrusel (menor = primero).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomepagePromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=150)),
                ('subtitle', models.CharField(blank=True, default='', max_length=200)),
                ('show_text', models.BooleanField(default=True, help_text='Si se desactiva, no se muestran título/subtítulo aunque existan.')),
                ('placement', models.CharField(choices=[('TOP', 'Top'), ('MID', 'Mid')], db_index=True, default='MID', help_text='Dónde se muestra esta promo en el Home (Top/Mid).', max_length=10)),
                ('image', models.ImageField(upload_to=apps.catalog.models.homepage_promo_upload_path)),
                ('alt_text', models.CharField(blank=True, default='', max_length=200)),
                ('cta_label', models.CharField(blank=True, default='Ver más', help_text="Texto del CTA (por ejemplo, 'Ver más').", max_length=80)),
                ('cta_url', models.CharField(blank=True, default='', help_text='Ruta relativa opcional (ej: /catalogo). Si está vacía, la tarjeta no tendrá link.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=1, help_text='Orden de aparición (menor = primero).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promo de Home',
                'verbose_name_plural': 'Promos de Home',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Identificador único (ej: 'brand-story', 'about', 'shipping-info').", max_length=60, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, default='', max_length=200)),
                ('content', models.TextField(help_text='Contenido principal (texto largo).')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sección de Home',
                'verbose_name_plural': 'Secciones de Home',
                'ordering': ['sort_order', '-updated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('stock', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('generic', 'Genérico'), ('size', 'Talla'), ('measure', 'Medida'), ('mug_type', 'Tipo de mug')], default='generic', editable=False, max_length=20)),
                ('value', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'ordering': ['product__name', 'kind', 'value', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.catalog.models.product_image_upload_path)),
                ('alt_text', models.CharField(blank=True, help_text="Texto alternativo para accesibilidad y SEO (ej: 'Camiseta roja talla M')", max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Marcar como imagen principal/portada de esta variante')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Orden de visualización (menor = primero)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(help_text='Variante del producto a la que pertenece esta imagen', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'Imagen de variante',
                'verbose_name_plural': 'Imágenes de variantes',
                'ordering': ['sort_order', 'is_primary', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'kind', 'value', 'color'), name='uniq_product_variant'),
        ),
    ]
