# Generated by Django 6.0.1 on 2026-02-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='uniq_product_variant',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'kind', 'value', 'color'), name='uniq_product_variant'),
        ),
    ]
