# Generated by Django 5.2.11 on 2026-02-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='uniq_product_variant_kind_value',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'kind', 'value', 'color'), name='uniq_product_variant_kind_value_color'),
        ),
    ]
