# Generated by Django 6.0.1 on 2026-02-06 18:18

import apps.catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_productvariant_uniq_product_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.catalog.models.product_image_upload_path)),
                ('alt_text', models.CharField(blank=True, help_text='Texto alternativo para accesibilidad y SEO', max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Marcar como imagen principal/portada')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Orden de visualización (menor = primero)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imágenes de producto',
                'ordering': ['sort_order', 'is_primary', 'created_at'],
            },
        ),
    ]
