# Generated by Django 5.2.11 on 2026-02-24 00:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_productvariant_uniq_product_variant_kind_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default='', max_length=32)),
                ('color', models.CharField(blank=True, default='', max_length=32)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category__name', 'value', 'color', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['product__name', 'value', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='uniq_product_variant_kind_value_color',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='kind',
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='category',
            name='variant_schema',
            field=models.CharField(choices=[('size_color', 'Talla + Color'), ('jean_size', 'Talla Jean'), ('no_variant', 'Sin variantes'), ('dimension', 'Medida/Dimensión')], db_index=True, default='size_color', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=140),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='value',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'value', 'color'), name='uniq_product_variant_value_color'),
        ),
        migrations.AddField(
            model_name='category',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='catalog.department'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('department', 'parent', 'slug'), name='uniq_category_department_parent_slug'),
        ),
        migrations.AddField(
            model_name='inventorypool',
            name='category',
            field=models.ForeignKey(help_text='Categoría leaf (Camisetas/Hoodies/Jean/etc).', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_pools', to='catalog.category'),
        ),
        migrations.AddConstraint(
            model_name='inventorypool',
            constraint=models.UniqueConstraint(fields=('category', 'value', 'color'), name='uniq_inventorypool_category_value_color'),
        ),
    ]
