# Generated by Django 5.2.11 on 2026-02-24 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ('catalog', '0003b_backfill_category_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='catalog.department'),
        ),
    ]
