# Generated by Django 6.0.1 on 2026-02-06 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_stock_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['sort_order', 'is_primary', 'created_at'], 'verbose_name': 'Imagen de variante', 'verbose_name_plural': 'Imágenes de variantes'},
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AddField(
            model_name='productimage',
            name='variant',
            field=models.ForeignKey(default=None, help_text='Variante del producto a la que pertenece esta imagen', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.productvariant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text="Texto alternativo para accesibilidad y SEO (ej: 'Camiseta roja talla M')", max_length=200),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Marcar como imagen principal/portada de esta variante'),
        ),
    ]
