# Generated by Django 5.2.11 on 2026-03-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_category_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='variant_schema',
            field=models.CharField(choices=[('size_color', 'Talla + Color'), ('jean_size', 'Talla Jean'), ('shoe_size', 'Talla Zapatilla'), ('no_variant', 'Sin variantes')], db_index=True, default='size_color', max_length=20),
        ),
    ]
