# Generated by Django 5.2.11 on 2026-03-07 14:53

import apps.catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_category_variant_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='', max_length=32)),
                ('image', models.ImageField(upload_to=apps.catalog.models.product_color_image_upload_path)),
                ('alt_text', models.CharField(blank=True, help_text="Texto alternativo para accesibilidad y SEO (ej: 'Camiseta negra')", max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Marcar como imagen principal/portada para este producto y color')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Orden de visualización (menor = primero)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='Producto al que pertenece esta imagen por color', on_delete=django.db.models.deletion.CASCADE, related_name='color_images', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Imagen por color',
                'verbose_name_plural': 'Imágenes por color',
                'ordering': ['sort_order', 'is_primary', 'created_at'],
            },
        ),
    ]
