# Generated by Django 6.0.1 on 2026-02-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_homepagebanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Identificador único (ej: 'brand-story', 'about', 'shipping-info').", max_length=60, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, default='', max_length=200)),
                ('content', models.TextField(help_text='Contenido principal (texto largo).')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sección de Home',
                'verbose_name_plural': 'Secciones de Home',
                'ordering': ['sort_order', '-updated_at', 'id'],
            },
        ),
    ]
