# Generated by Django 5.2.11 on 2026-03-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productcolorimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='home_marquee_order',
            field=models.PositiveIntegerField(default=0, help_text='Orden manual en el marquee del Home (menor = primero).'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_in_home_marquee',
            field=models.BooleanField(db_index=True, default=False, help_text='Si está activo, el producto aparecerá en el marquee del Home.'),
        ),
    ]
