# Generated by Django 6.0.1 on 2026-02-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_homepagesection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagebanner',
            name='cta_url',
            field=models.CharField(blank=True, default='', help_text='Usa una ruta relativa. Ej: /catalogo (NO uses http(s)://, localhost, 127.0.0.1, 192.168.x.x ni dominios .trycloudflare.com).', max_length=255),
        ),
    ]
