# Generated by Django 6.0.1 on 2026-02-15 22:25

import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_homepagebanner_cta_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepagePromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, default='', max_length=200)),
                ('image', models.ImageField(upload_to=apps.catalog.models.homepage_promo_upload_path)),
                ('alt_text', models.CharField(blank=True, default='', max_length=200)),
                ('cta_label', models.CharField(blank=True, default='Ver más', help_text="Texto del CTA (por ejemplo, 'Ver más').", max_length=80)),
                ('cta_url', models.CharField(blank=True, default='', help_text='Ruta relativa opcional (ej: /catalogo). Si está vacía, la tarjeta no tendrá link.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=1, help_text='Orden de aparición (menor = primero).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promo de Home',
                'verbose_name_plural': 'Promos de Home',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
