# Generated by Django 5.2.11 on 2026-03-27 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_home_marquee_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySizeGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('subtitle', models.TextField(blank=True, default='')),
                ('columns_json', models.JSONField(blank=True, default=list)),
                ('rows_json', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='size_guide', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Guía de medidas por categoría',
                'verbose_name_plural': 'Guías de medidas por categoría',
            },
        ),
    ]
