# Generated by Django 6.0.1 on 2026-02-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_homepagepromo'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagepromo',
            name='placement',
            field=models.CharField(choices=[('TOP', 'Top'), ('MID', 'Mid')], db_index=True, default='MID', help_text='Dónde se muestra esta promo en el Home (Top/Mid).', max_length=10),
        ),
        migrations.AlterField(
            model_name='homepagepromo',
            name='title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
