# Generated by Django 6.0.1 on 2026-02-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_homepagepromo_placement_alter_homepagepromo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagepromo',
            name='show_text',
            field=models.BooleanField(default=True, help_text='Si se desactiva, no se muestran título/subtítulo aunque existan.'),
        ),
    ]
