# Generated by Django 6.0.1 on 2026-02-16 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_homepagepromo_show_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagebanner',
            name='show_text',
            field=models.BooleanField(default=True, help_text='Si se desactiva, no se muestran título/subtítulo/descripcion aunque existan.'),
        ),
        migrations.AlterField(
            model_name='homepagebanner',
            name='title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
