# Generated by Django 5.2.11 on 2026-08-26 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_homepagepromo_cta_label_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre interno (ej: Día de la Mujer 2026)', max_length=200)),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed_amount', 'Monto fijo (COP)')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Porcentaje (ej: 5 para 5%) o monto fijo en COP (ej: 10000).', max_digits=10)),
                ('scope', models.CharField(choices=[('store_wide', 'Toda la tienda'), ('department', 'Departamento'), ('category', 'Categoría'), ('product', 'Producto específico')], default='store_wide', max_length=20)),
                ('starts_at', models.DateTimeField(help_text='Fecha y hora de inicio del descuento.')),
                ('ends_at', models.DateTimeField(blank=True, help_text='Dejar vacío para descuento sin expiración.', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Mayor prioridad prevalece entre reglas del mismo scope.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Solo si scope = categoría.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_rules', to='catalog.category')),
                ('department', models.ForeignKey(blank=True, help_text='Solo si scope = departamento.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_rules', to='catalog.department')),
                ('product', models.ForeignKey(blank=True, help_text='Solo si scope = producto.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_rules', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Regla de descuento',
                'verbose_name_plural': 'Reglas de descuento',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
